#!/usr/bin/env ruby

require_relative '../lib/pull_request_ai_generator'

generator = PullRequestAIGenerator.new(ARGV)

case generator.options[:command]
when :init
  generator.init
else
  generator.run
end